---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1575278/public_html/bokin
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp css/style.css $DEPLOYPATH
    - /bin/cp js/scripts.js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH